[package]
name = "orion_lib"
version = "4.0.0"
edition = "2021"
description = "A library for parsing and executing the Orion Programming Language"
license-file = "LICENSE"
documentation = "https://docs.rs/orion_lib"
repository = "https://github.com/Solarcode-org/orion-lib"
readme = "README.md"
keywords = ["programming_language"]
categories = ["compilers"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.14.0"
